modelOptions:
  # Architecture
  promptTokenBatchSize: 128
  genTokenBatchSize: 1
  cacheSize: 1024
  hiddenSize: 4096
  numHead: 32
  numLayer: 32
  maxTokenLength: 4096
  rotEmbBase: 10000
  # Types
  modelInputType: INT16
  modelOutputType: INT16
  cacheType: INT16
  maskType: INT16
  rotEmbType: INT16

runtimeOptions:
  # Special tokens that determines the inference behavior.
  specialTokens:
    bosId: 1      # BOS token Id, required to set.
    eosId: 2      # EOS token Id, required to set.
    addBos: true  # Prepend BOS token during tokenization. Default to false if not set.

  tokenizerPath: /data/local/tmp/llm_sdk/llama2_7b/tokenizer.model

  tokenEmbPath: /data/local/tmp/llm_sdk/llama2_7b/embedding_Llama-2-7b-hf.bin

  dlaPromptPaths:
    - /data/local/tmp/llm_sdk/llama2_7b/llama2_7b_sym4W_sym16A_Overall_128t1024c_0.dla
    - /data/local/tmp/llm_sdk/llama2_7b/llama2_7b_sym4W_sym16A_Overall_128t1024c_1.dla
  dlaGenPaths:
    - /data/local/tmp/llm_sdk/llama2_7b/llama2_7b_sym4W_sym16A_Overall_1t1024c_0.dla
    - /data/local/tmp/llm_sdk/llama2_7b/llama2_7b_sym4W_sym16A_Overall_1t1024c_1.dla
  sharedWeightsPaths:
    - /data/local/tmp/llm_sdk/llama2_7b/shared_weights_0.bin
    - /data/local/tmp/llm_sdk/llama2_7b/shared_weights_1.bin
